spring.application.name=server

#Details for PostgresSQL
spring.datasource.url = ${PSQL_URL}
spring.datasource.username = ${PSQL_USERNAME}
spring.datasource.password = ${PSQL_PASSWORD}

spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto = update