name: CI Build and Test

on:
  pull_request:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK 21
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '21'
          java-package: jdk
          jdk architecture: x64

      - name: Build project
        working-directory: ./server
        run: ./gradlew clean build -x test

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK 21
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '21'
          java-package: jdk
          jdk architecture: x64

      - name: Run tests
        working-directory: ./server
        run: ./gradlew test
